In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Create Numpy Array With Numpy Function 


In [2]:
# Array filled with 0`s
# Array filled with 1`s
# Create an empty array
# An array with a range of element 
# Array diagonal element filled with 1`s
# Create an array with values that are spaced linearly in a specified interval


# Zeros
Array made with zeros

In [3]:
# making array with zero 

import numpy as np


In [4]:
ar_zero = np.zeros(4)
print(ar_zero) # here the array make with zeros one D array  

[0. 0. 0. 0.]


In [5]:
# making two diamension array with zero 2 D array 

ar_zero = np.zeros((3,4))
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones
Array made with ones

In [6]:
# we made another array with one 

ar_one = np.ones(5)
print(ar_one) # the out put is one D array 

[1. 1. 1. 1. 1.]


In [7]:
ar_one = np.ones((3,3))
print(type(ar_one))
print(ar_one)

print(ar_one.ndim)   # this is a 2 D array this function is use to check the Dimen---

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


# Empty 
Array made with empty function 

In [8]:
# we made an other array that is empty array 
#  we made empty array 

ar_em = np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


# Range
Array made with range function 

In [9]:
# we made an other array with the help of range function 

ar_rn = np.arange(4) # range perform the operation from zero to n-1 
print(ar_rn)
print(type(ar_rn))

[0 1 2 3]
<class 'numpy.ndarray'>


# Diagonal 
Array made with diagonal element

"only diagonal element will be 1 and othe will be 0"

for diagonal function we use ""eye"" function 

In [10]:
ar_dia = np.eye(3)
print(ar_dia) # array made with diagonal element and use the "eye" function 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np
ar_dia = np.eye(3,3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# line space 

in that function we use "linespace" function that create a gap in the array 

In [12]:
# we use a specific function thats put a gap in te array function

ar_line = np.linspace(0,20,num=5)
print(ar_line)

[ 0.  5. 10. 15. 20.]
